### ISSUE TITLE
Change VM resolution

### ISSUE THREAD

**Issue by mobilegmYT** [Itai-Nelken/RPi-QEMU-VM-scripts#2]
The VMs are locked at a square resolution, is there a way to change them to 720p or 1080p so it fills up the whole screen?

**Comment by Itai-Nelken** [comment]
Use the OS's controls.
On win98: control panel>displaand on macos921: find the icon with something that looks like a screen with black pixels in it on the dock. click on it to see a list of resolutions.

Just keep in mind that performance will be slightly worse on larger resolutions.
Also check the qemu menu, it has a option for fullscreen.

**Comment by SrIzan10** [comment]
Or ctrl+alt+f for fullscreen (writing in a phone is pretty bad, sorry)

**Comment by SrIzan10** [comment]
@Itai-Nelken ’s solution works. @mobilegmYT you can close the issue if it works for you

**Comment by Itai-Nelken** [comment]
no, don't close it yet. I want to add this to the documentation but I need a reminder (this issue).
@Reyansh-Khobragade do you want to add it?

**Comment by Reyansh-Khobragade** [comment]
> no, don't close it yet. I want to add this to the documentation but I need a reminder (this issue).
> @Reyansh-Khobragade do you want to add it?

Maybe you can add it will be nice for those who wanted to change stuff.

**Comment by Itai-Nelken** [comment]
done
